#!/usr/bin/env python3
"""
5.2_image_gen.py — Image generation experiment: SDXL inference and scheduler comparison.

Usage:
  python 5.2_image_gen.py --demo
  python 5.2_image_gen.py --config image_config.yaml
  python 5.2_image_gen.py --demo --out ./reports/image_report.md

Designed for a single 24GB GPU.
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


@dataclass
class GenerationResult:
    scheduler: str
    steps: int
    time_s: float
    resolution: str
    cfg_scale: float


def run_demo() -> list[GenerationResult]:
    """Run SDXL inference demo with scheduler comparison."""
    import torch
    from diffusers import (
        StableDiffusionXLPipeline,
        DPMSolverMultistepScheduler,
        EulerDiscreteScheduler,
        EulerAncestralDiscreteScheduler,
    )

    print("Loading SDXL pipeline...")
    pipe = StableDiffusionXLPipeline.from_pretrained(
        "stabilityai/stable-diffusion-xl-base-1.0",
        torch_dtype=torch.float16, variant="fp16", use_safetensors=True,
    ).to("cuda")
    pipe.enable_vae_tiling()

    prompt = "A futuristic city at sunset, cyberpunk aesthetic, detailed architecture, 8k"
    negative = "blurry, low quality, distorted"

    schedulers = [
        ("DPM++ 2M Karras", DPMSolverMultistepScheduler, 25),
        ("Euler", EulerDiscreteScheduler, 25),
        ("Euler Ancestral", EulerAncestralDiscreteScheduler, 25),
    ]

    results = []
    output_dir = Path("./demo_outputs")
    output_dir.mkdir(exist_ok=True)

    for name, sched_cls, steps in schedulers:
        pipe.scheduler = sched_cls.from_config(pipe.scheduler.config)

        # Warmup
        _ = pipe(prompt, num_inference_steps=3, output_type="latent", width=512, height=512)
        torch.cuda.synchronize()

        start = time.perf_counter()
        image = pipe(
            prompt, negative_prompt=negative,
            num_inference_steps=steps, guidance_scale=7.5,
            width=1024, height=1024,
            generator=torch.Generator("cuda").manual_seed(42),
        ).images[0]
        torch.cuda.synchronize()
        elapsed = time.perf_counter() - start

        image.save(output_dir / f"sdxl_{name.replace(' ', '_').lower()}.png")
        results.append(GenerationResult(
            scheduler=name, steps=steps, time_s=round(elapsed, 2),
            resolution="1024x1024", cfg_scale=7.5,
        ))
        print(f"  {name}: {elapsed:.2f}s")

    return results


def render_report(results: list[GenerationResult]) -> str:
    """Render image generation report."""
    lines = [
        "---",
        "tags: [ai-experiments, image-generation, sdxl, practice]",
        "chapter: 5.2",
        "type: image-gen-report",
        f"generated: {datetime.now().isoformat(timespec='seconds')}",
        "---\n",
        "# Image Generation Report\n",
        f"> Generated by `5.2_image_gen.py` on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
        "## Scheduler Comparison\n",
        "| Scheduler | Steps | Time | Resolution | CFG |",
        "|-----------|-------|------|-----------|-----|",
    ]
    for r in results:
        lines.append(f"| {r.scheduler} | {r.steps} | {r.time_s}s | {r.resolution} | {r.cfg_scale} |")

    if results:
        fastest = min(results, key=lambda x: x.time_s)
        lines.append(f"\n**Fastest:** {fastest.scheduler} at {fastest.time_s}s")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Image generation experiment")
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--config", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    if args.demo:
        results = run_demo()
    else:
        print("Use --demo to run SDXL scheduler comparison.")
        return

    out_path = args.out or Path(__file__).parent.parent / "5.2_image_report.md"
    report = render_report(results)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(f"\nReport saved: {out_path}")


if __name__ == "__main__":
    main()
