#!/usr/bin/env python3
"""
5.3_finetune_llm.py — QLoRA fine-tuning experiment runner.

Fine-tunes a language model with QLoRA and emits a markdown metrics report.

Usage:
  python 5.3_finetune_llm.py --demo
  python 5.3_finetune_llm.py --config finetune_config.yaml
  python 5.3_finetune_llm.py --demo --out ./reports/finetune_report.md

Designed for a single 24GB GPU.
"""

from __future__ import annotations

import argparse
import json
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


@dataclass
class TrainingMetrics:
    epoch: int
    step: int
    loss: float
    learning_rate: float
    gpu_memory_gb: float
    tokens_per_second: float


def run_demo_finetune() -> list[TrainingMetrics]:
    """Run a minimal QLoRA fine-tune for validation."""
    import torch
    from datasets import Dataset
    from transformers import (
        AutoModelForCausalLM, AutoTokenizer,
        BitsAndBytesConfig, TrainingArguments,
    )
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
    from trl import SFTTrainer

    # Use a small model for demo
    model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )

    print(f"Loading model: {model_name}")
    model = AutoModelForCausalLM.from_pretrained(
        model_name, quantization_config=bnb_config, device_map="auto"
    )
    model = prepare_model_for_kbit_training(model)

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    tokenizer.pad_token = tokenizer.eos_token

    lora_config = LoraConfig(
        r=16, lora_alpha=32,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        lora_dropout=0.05, bias="none", task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    trainable, total = model.get_nb_trainable_parameters()
    print(f"Trainable: {trainable:,} / {total:,} ({100*trainable/total:.2f}%)")

    # Synthetic dataset for demo
    examples = [
        {"text": f"<|user|>\nWhat is {i}+{i}?<|assistant|>\n{i}+{i} = {2*i}"}
        for i in range(100)
    ]
    dataset = Dataset.from_list(examples)

    training_args = TrainingArguments(
        output_dir="./demo_qlora_output",
        num_train_epochs=1,
        per_device_train_batch_size=4,
        gradient_accumulation_steps=2,
        learning_rate=2e-4,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        bf16=True,
        logging_steps=5,
        save_strategy="no",
        max_steps=20,  # Short demo
        report_to="none",
    )

    trainer = SFTTrainer(
        model=model, train_dataset=dataset, tokenizer=tokenizer,
        args=training_args, dataset_text_field="text", max_seq_length=128,
    )

    start = time.perf_counter()
    result = trainer.train()
    elapsed = time.perf_counter() - start

    # Collect metrics
    metrics = []
    for log in trainer.state.log_history:
        if "loss" in log:
            mem = torch.cuda.max_memory_allocated() / 1024**3
            metrics.append(TrainingMetrics(
                epoch=int(log.get("epoch", 0)),
                step=log.get("step", 0),
                loss=log["loss"],
                learning_rate=log.get("learning_rate", 0),
                gpu_memory_gb=round(mem, 2),
                tokens_per_second=round(100 * 128 / elapsed, 0),
            ))

    print(f"Training complete in {elapsed:.1f}s")
    print(f"Final loss: {result.training_loss:.4f}")
    return metrics


def render_report(metrics: list[TrainingMetrics], config: dict) -> str:
    """Render training metrics as markdown report."""
    lines = [
        "---",
        "tags: [ai-experiments, fine-tuning, qlora, practice]",
        "chapter: 5.3",
        "type: training-report",
        f"generated: {datetime.now().isoformat(timespec='seconds')}",
        "---\n",
        "# LLM Fine-tuning Report\n",
        f"> Generated by `5.3_finetune_llm.py` on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
        "## Configuration\n",
        f"- Model: {config.get('model', 'TinyLlama-1.1B')}",
        f"- Method: QLoRA (4-bit NF4)",
        f"- Rank: {config.get('rank', 16)}",
        f"- Alpha: {config.get('alpha', 32)}",
        f"- Learning rate: {config.get('lr', '2e-4')}",
        f"- Batch size: {config.get('batch_size', 4)}\n",
        "## Training Metrics\n",
        "| Step | Loss | LR | GPU Memory |",
        "|------|------|----|-----------|",
    ]

    for m in metrics:
        lines.append(f"| {m.step} | {m.loss:.4f} | {m.learning_rate:.2e} | {m.gpu_memory_gb} GB |")

    if metrics:
        lines.append(f"\n## Summary\n")
        lines.append(f"- Final loss: {metrics[-1].loss:.4f}")
        lines.append(f"- Peak GPU memory: {max(m.gpu_memory_gb for m in metrics)} GB")
        lines.append(f"- Throughput: ~{metrics[-1].tokens_per_second:.0f} tokens/s")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="QLoRA fine-tuning experiment")
    parser.add_argument("--demo", action="store_true", help="Run minimal demo fine-tune")
    parser.add_argument("--config", type=Path, default=None, help="YAML/JSON config")
    parser.add_argument("--out", type=Path, default=None, help="Output report path")
    args = parser.parse_args()

    config = {"model": "TinyLlama-1.1B", "rank": 16, "alpha": 32, "lr": "2e-4", "batch_size": 4}
    if args.config and args.config.exists():
        with open(args.config) as f:
            config.update(json.load(f))

    if args.demo:
        metrics = run_demo_finetune()
    else:
        print("Use --demo for quick validation or --config for full training.")
        return

    out_path = args.out or Path(__file__).parent.parent / "5.3_finetune_report.md"
    report = render_report(metrics, config)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(f"Report saved: {out_path}")


if __name__ == "__main__":
    main()
