#!/usr/bin/env python3
"""
5.6_voice_pipeline.py — Voice pipeline experiment: ASR transcription benchmark.

Usage:
  python 5.6_voice_pipeline.py --demo
  python 5.6_voice_pipeline.py --config voice_config.yaml --audio recording.wav
  python 5.6_voice_pipeline.py --demo --out ./reports/voice_report.md

Designed for a single 24GB GPU.
"""

from __future__ import annotations

import argparse
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


@dataclass
class TranscriptionResult:
    model_size: str
    audio_duration_s: float
    transcription_time_s: float
    realtime_factor: float
    text: str
    language: str


def run_demo() -> list[TranscriptionResult]:
    """Run Whisper transcription demo with model size comparison."""
    try:
        from faster_whisper import WhisperModel
        use_faster = True
    except ImportError:
        import whisper
        use_faster = False

    # Generate synthetic audio for demo (sine wave with speech-like duration)
    import numpy as np
    import tempfile
    import soundfile as sf

    # Create a 10-second test audio file
    sr = 16000
    duration = 10.0
    t = np.linspace(0, duration, int(sr * duration))
    # Mix of frequencies to simulate speech-like signal
    audio = 0.3 * np.sin(2 * np.pi * 200 * t) + 0.2 * np.sin(2 * np.pi * 400 * t)
    audio += 0.1 * np.random.randn(len(audio))  # Add noise

    tmp_path = Path(tempfile.mktemp(suffix=".wav"))
    sf.write(str(tmp_path), audio, sr)

    models_to_test = ["tiny", "base"]  # Small models for demo
    results = []

    for model_size in models_to_test:
        print(f"  Testing {model_size}...")

        if use_faster:
            model = WhisperModel(model_size, device="cpu", compute_type="int8")
            start = time.perf_counter()
            segments, info = model.transcribe(str(tmp_path), beam_size=1)
            text = " ".join(s.text for s in segments)
            lang = info.language
        else:
            model = whisper.load_model(model_size)
            start = time.perf_counter()
            result = model.transcribe(str(tmp_path), fp16=False)
            text = result["text"]
            lang = result.get("language", "en")

        elapsed = time.perf_counter() - start
        rtf = duration / elapsed

        results.append(TranscriptionResult(
            model_size=model_size,
            audio_duration_s=duration,
            transcription_time_s=round(elapsed, 3),
            realtime_factor=round(rtf, 1),
            text=text.strip()[:100] if text.strip() else "(silence/noise detected)",
            language=lang,
        ))
        print(f"    {model_size}: {elapsed:.2f}s ({rtf:.0f}× realtime)")

    tmp_path.unlink(missing_ok=True)
    return results


def render_report(results: list[TranscriptionResult]) -> str:
    """Render voice pipeline report."""
    lines = [
        "---",
        "tags: [ai-experiments, voice, whisper, asr, practice]",
        "chapter: 5.6",
        "type: voice-report",
        f"generated: {datetime.now().isoformat(timespec='seconds')}",
        "---\n",
        "# Voice Pipeline Report\n",
        f"> Generated by `5.6_voice_pipeline.py` on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
        "## ASR Model Comparison\n",
        "| Model | Audio | Transcription Time | Realtime Factor | Language |",
        "|-------|-------|-------------------|-----------------|----------|",
    ]
    for r in results:
        lines.append(f"| whisper-{r.model_size} | {r.audio_duration_s}s | {r.transcription_time_s}s | {r.realtime_factor}× | {r.language} |")

    lines.append("\n## Notes\n")
    lines.append("- Realtime factor > 1× means faster than realtime")
    lines.append("- For production: use `faster-whisper` with `large-v3` on GPU")
    lines.append("- Expected: large-v3 on RTX 4090 achieves 50-70× realtime")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Voice pipeline experiment")
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--config", type=Path, default=None)
    parser.add_argument("--audio", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    if args.demo:
        print("Running Whisper ASR demo...")
        results = run_demo()
    else:
        print("Use --demo for quick validation or --audio with a WAV file.")
        return

    out_path = args.out or Path(__file__).parent.parent / "5.6_voice_report.md"
    report = render_report(results)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(f"\nReport saved: {out_path}")


if __name__ == "__main__":
    main()
