#!/usr/bin/env python3
"""
5.7_multimodal.py — Multimodal experiment: vision-language inference.

Usage:
  python 5.7_multimodal.py --demo
  python 5.7_multimodal.py --config multimodal_config.yaml --image photo.jpg
  python 5.7_multimodal.py --demo --out ./reports/multimodal_report.md

Designed for a single 24GB GPU.
"""

from __future__ import annotations

import argparse
import time
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


@dataclass
class VLMResult:
    image: str
    question: str
    answer: str
    latency_s: float
    tokens_generated: int


def run_demo() -> list[VLMResult]:
    """Run VLM demo with synthetic test (model loading validation)."""
    import torch
    from transformers import AutoProcessor, AutoModelForCausalLM
    from PIL import Image
    import numpy as np

    # Use a small model for demo validation
    model_name = "microsoft/Florence-2-base"
    print(f"Loading VLM: {model_name}")

    model = AutoModelForCausalLM.from_pretrained(
        model_name, torch_dtype=torch.float32, trust_remote_code=True
    )
    processor = AutoProcessor.from_pretrained(model_name, trust_remote_code=True)

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = model.to(device)

    # Create synthetic test images
    test_cases = [
        {"desc": "red_square", "question": "<CAPTION>", "image": _make_test_image("red")},
        {"desc": "blue_circle", "question": "<CAPTION>", "image": _make_test_image("blue")},
        {"desc": "gradient", "question": "<DETAILED_CAPTION>", "image": _make_test_image("gradient")},
    ]

    results = []
    for tc in test_cases:
        start = time.perf_counter()

        inputs = processor(text=tc["question"], images=tc["image"], return_tensors="pt").to(device)
        generated_ids = model.generate(
            input_ids=inputs["input_ids"],
            pixel_values=inputs["pixel_values"],
            max_new_tokens=100,
        )
        text = processor.batch_decode(generated_ids, skip_special_tokens=False)[0]
        parsed = processor.post_process_generation(text, task=tc["question"], image_size=tc["image"].size)

        elapsed = time.perf_counter() - start
        answer = str(parsed.get(tc["question"], text))[:200]

        results.append(VLMResult(
            image=tc["desc"], question=tc["question"],
            answer=answer, latency_s=round(elapsed, 2),
            tokens_generated=len(generated_ids[0]) - len(inputs["input_ids"][0]),
        ))
        print(f"  {tc['desc']}: {answer[:80]}...")

    return results


def _make_test_image(style: str):
    """Create a synthetic test image."""
    from PIL import Image
    import numpy as np

    img = np.zeros((224, 224, 3), dtype=np.uint8)
    if style == "red":
        img[50:174, 50:174] = [255, 0, 0]
    elif style == "blue":
        for y in range(224):
            for x in range(224):
                if (x - 112)**2 + (y - 112)**2 < 60**2:
                    img[y, x] = [0, 0, 255]
    elif style == "gradient":
        for x in range(224):
            img[:, x] = [int(255 * x / 224), 0, int(255 * (224 - x) / 224)]
    return Image.fromarray(img)


def render_report(results: list[VLMResult]) -> str:
    """Render multimodal report."""
    lines = [
        "---",
        "tags: [ai-experiments, multimodal, vlm, practice]",
        "chapter: 5.7",
        "type: multimodal-report",
        f"generated: {datetime.now().isoformat(timespec='seconds')}",
        "---\n",
        "# Multimodal Experiment Report\n",
        f"> Generated by `5.7_multimodal.py` on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n",
        "## VLM Inference Results\n",
        "| Image | Task | Answer | Latency | Tokens |",
        "|-------|------|--------|---------|--------|",
    ]
    for r in results:
        answer_short = r.answer[:60].replace("|", "\\|")
        lines.append(f"| {r.image} | {r.question} | {answer_short} | {r.latency_s}s | {r.tokens_generated} |")

    avg_latency = sum(r.latency_s for r in results) / len(results) if results else 0
    lines.append(f"\n**Average latency:** {avg_latency:.2f}s")
    lines.append("\n## Notes\n")
    lines.append("- Demo uses Florence-2-base (lightweight)")
    lines.append("- For production: use Qwen2-VL-7B or InternVL2.5-8B")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Multimodal VLM experiment")
    parser.add_argument("--demo", action="store_true")
    parser.add_argument("--config", type=Path, default=None)
    parser.add_argument("--image", type=Path, default=None)
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args()

    if args.demo:
        print("Running multimodal VLM demo...")
        results = run_demo()
    else:
        print("Use --demo for quick validation or --image with a file.")
        return

    out_path = args.out or Path(__file__).parent.parent / "5.7_multimodal_report.md"
    report = render_report(results)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(report, encoding="utf-8")
    print(f"\nReport saved: {out_path}")


if __name__ == "__main__":
    main()
