#!/usr/bin/env python3
"""
1.1_setup_tooling.py — Environment validation lab for Chapter 1.1
(Setup, Tooling & Project Structure).

Detects platform, validates Python installation, checks for required tools,
and emits an Obsidian-formatted markdown report.

Usage:
  python 1.1_setup_tooling.py
  python 1.1_setup_tooling.py --out ../1.1_lab_report.md
  python 1.1_setup_tooling.py --demo

Exit code 0 on success, 1 if critical checks fail.
"""
from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def detect_platform() -> dict[str, str]:
    return {
        "os": platform.system(),
        "os_version": platform.version(),
        "architecture": platform.machine(),
        "python_version": platform.python_version(),
        "python_implementation": platform.python_implementation(),
        "python_executable": sys.executable,
        "prefix": sys.prefix,
        "base_prefix": sys.base_prefix,
        "venv_active": sys.prefix != sys.base_prefix,
    }


def check_tool(name: str, version_flag: str = "--version") -> dict[str, str | bool]:
    path = shutil.which(name)
    if not path:
        return {"name": name, "available": False, "path": "", "version": ""}
    try:
        result = subprocess.run(
            [path, version_flag], capture_output=True, text=True, timeout=10
        )
        version = (result.stdout + result.stderr).strip().split("\n")[0]
    except Exception as e:
        version = f"Error: {e}"
    return {"name": name, "available": True, "path": path, "version": version}


def check_venv_isolation() -> dict[str, str | bool]:
    """Verify that venv isolation works."""
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        venv_path = Path(tmp) / "test_venv"
        try:
            import venv
            venv.create(str(venv_path), with_pip=False)
            cfg = venv_path / "pyvenv.cfg"
            return {"works": True, "cfg_exists": cfg.exists()}
        except Exception as e:
            return {"works": False, "error": str(e)}


def render_report(plat: dict, tools: list[dict], venv: dict) -> str:
    now = datetime.now().isoformat(timespec="seconds")
    lines = [
        "---",
        "tags: [python, setup, lab-report, practice]",
        "type: lab-report",
        f"generated: {now}",
        "chapter: 1.1",
        "---\n",
        "*Back to [[../1.1 - Setup, Tooling & Project Structure|Chapter 1.1]]*\n",
        "# Chapter 1.1 — Lab Report: Environment Validation\n",
        f"> Generated by `scripts/1.1_setup_tooling.py` on {now}\n",
        "---\n",
        "## Platform Detection\n",
        f"| Property | Value |",
        f"|----------|-------|",
    ]
    for k, v in plat.items():
        lines.append(f"| {k} | `{v}` |")

    lines.extend(["\n## Tool Availability\n", "| Tool | Available | Version | Path |", "|------|-----------|---------|------|"])
    for t in tools:
        status = "✅" if t["available"] else "❌"
        lines.append(f"| {t['name']} | {status} | {t.get('version', '')} | `{t.get('path', '')}` |")

    lines.extend(["\n## Virtual Environment Isolation\n"])
    if venv.get("works"):
        lines.append("✅ `venv.create()` works correctly. `pyvenv.cfg` generated.")
    else:
        lines.append(f"❌ venv creation failed: {venv.get('error', 'unknown')}")

    # Summary
    all_critical = all(t["available"] for t in tools if t["name"] in ("python", "pip"))
    lines.extend([
        "\n## Summary\n",
        f"- Critical tools: {'✅ All present' if all_critical else '❌ Missing critical tools'}",
        f"- Python version: {'✅ 3.11+' if tuple(int(x) for x in plat['python_version'].split('.')[:2]) >= (3, 11) else '⚠️ Upgrade recommended'}",
        f"- Venv active: {'✅ Yes' if plat['venv_active'] else '⚠️ No (activate a venv)'}",
    ])
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Validate Python development environment")
    parser.add_argument("--out", type=Path, default=None, help="Output report path")
    parser.add_argument("--demo", action="store_true", help="Print report to stdout only")
    args = parser.parse_args()

    plat = detect_platform()
    tools = [
        check_tool("python", "--version"),
        check_tool("pip", "--version"),
        check_tool("uv", "--version"),
        check_tool("ruff", "--version"),
        check_tool("mypy", "--version"),
        check_tool("pytest", "--version"),
        check_tool("git", "--version"),
        check_tool("docker", "--version"),
    ]
    venv = check_venv_isolation()

    report = render_report(plat, tools, venv)

    if args.demo:
        print(report)
    else:
        out_path = args.out or (Path(__file__).resolve().parent.parent / "1.1_lab_report.md")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(report, encoding="utf-8")
        print(f"✓ Report written to {out_path}")

    # Exit code based on critical checks
    critical_ok = all(t["available"] for t in tools if t["name"] in ("python", "pip"))
    sys.exit(0 if critical_ok else 1)


if __name__ == "__main__":
    main()
